# Generated by Django 3.2.3 on 2021-06-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0008_auto_20210614_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('inprogress', 'Inprogress'), ('lost', 'Lost'), ('won', 'Won'), ('new', 'New'), ('contacted', 'Contacted')], default='new', max_length=25),
        ),
    ]
