# Generated by Django 3.2.3 on 2021-06-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0009_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('medium', 'Medium'), ('high', 'High'), ('low', 'Low')], default='medium', max_length=25),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('lost', 'Lost'), ('won', 'Won'), ('inprogress', 'Inprogress'), ('contacted', 'Contacted'), ('new', 'New')], default='new', max_length=25),
        ),
    ]
